lib/sparkle_server_web/router.ex
defmodule SparkleServerWeb.Router do
  use SparkleServerWeb, :router

  import SparkleServerWeb.UserAuth

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {SparkleServerWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
    plug(SparkleServerWeb.Plugs.CmsContent)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :appcast do
    plug(:accepts, ["html", "xml"])
    plug(:put_root_layout, false)
    plug(:put_layout, false)
  end

  # Other scopes may use custom stacks.
  # scope "/api", SparkleServerWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)

      live_dashboard("/dashboard", metrics: SparkleServerWeb.Telemetry)
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through(:browser)

      forward("/mailbox", Plug.Swoosh.MailboxPreview)
    end
  end

  scope "/", SparkleServerWeb do
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/apps/:slug", AppsController, :show)
    get("/apps/:id/images/:image", AppsController, :images_show)
  end

  scope "/updates", SparkleServerWeb do
    pipe_through(:appcast)

    get("/:slug", AppcastController, :show)
  end

  scope "/", SparkleServerWeb do
    pipe_through([:browser, :require_authenticated_user])

    get("/admin", AdminController, :index)

    get("/admin/settings/edit", AdminController, :settings_edit)
    post("/admin/settings", AdminController, :settings_update)
    put("/admin/settings", AdminController, :settings_update)

    get("/admin/apps/new", AdminController, :apps_new)
    post("/admin/apps", AdminController, :apps_create)
    get("/admin/apps/:id/edit", AdminController, :apps_edit)
    put("/admin/apps/:id", AdminController, :apps_update)

    get("/admin/apps/:id/versions", AdminController, :apps_versions_index)
    get("/admin/apps/:id/versions/new", AdminController, :apps_versions_new)
    post("/admin/apps/:id/versions", AdminController, :apps_versions_create)
    get("/admin/apps/:id/versions/:version_id/edit", AdminController, :apps_versions_edit)
    put("/admin/apps/:id/versions/:version_id", AdminController, :apps_versions_update)

    get("/admin/apps/:id/metrics", AdminController, :apps_metrics_index)
    get("/admin/apps/:id/metrics/summaries", AdminController, :apps_metrics_summaries_index)
  end

  ## Authentication routes

  scope "/", SparkleServerWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
  end

  scope "/", SparkleServerWeb do
    pipe_through([:browser])

    delete("/users/log_out", UserSessionController, :delete)
  end
end

lib/sparkle_server_web/views/layout_view.ex
defmodule SparkleServerWeb.LayoutView do
  use SparkleServerWeb, :view

  def meta_tags(attrs_list) do
    Enum.map(attrs_list, &meta_tag/1)
  end

  def meta_tag(attrs) do
    tag(:meta, Enum.into(attrs, []))
  end

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/sparkle_server_web/templates/layout/app.html.heex
<section id="main" class="pt-10">
  <p class="alert alert-info max-w-[40rem] mx-auto" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger max-w-[40rem] mx-auto" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</section>

lib/sparkle_server_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/sparkle_server_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= if assigns[:meta_attrs], do: meta_tags(assigns[:meta_attrs]) %>
    <%= live_title_tag assigns[:page_title] || "SparkleServer", suffix: " · SparkleServer" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <div class="relative overflow-hidden min-h-screen flex flex-col bg-circle">
      <header class="absolute top-0 left-0 right-0 z-20">
        <nav class="max-w-[75rem] mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div class="flex justify-between items-center border-b-2 border-gray-100 py-6 md:justify-start md:space-x-10">
            <div class="flex justify-start lg:w-0 lg:flex-1">
              <a href="/" class="font-extrabold tracking-tight text-gray-900">
                <%= @settings.site_name %>
              </a>
            </div>
            <nav class="hidden md:flex space-x-10">
              <%= if @current_user do %>
              <%= link "Admin", to: Routes.admin_path(@conn, :index), class: "text-base font-medium text-gray-500 hover:text-gray-900" %>
              <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "text-base font-medium text-gray-500 hover:text-gray-900" %>
              <% end %>
            </nav>
          </div>
        </nav>
      </header>
      <%= @inner_content %>
      <div class="flex-shrink bg-dark-secondary">
        <div class="container mx-auto">
          <div class="flex justify-center flex-grow flex-shrink-0 lg:flex-grow-0">
            <div class="flex py-5">
              <p class="text-white text-sm px-5">&copy; 2022 Tim</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>